import {useEffect,useState} from "react";
import {CalendarDays,Check,ChevronLeft,ChevronRight,Clock,Link2,Plus,RefreshCw,Users,X} from "lucide-react";
import {Dialog,DialogContent,DialogDescription,DialogTitle} from "@/components/ui/dialog";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {toast} from "sonner";
import {type Poll,type Answer,type Slot,dateKey,dayLabel,monday} from "@/lib/schedule";

type Props={poll:Poll;answers:Answer[];profile:{id:string;name:string}|null;demo:boolean;owner:boolean;week:Date;onWeekChange:(date:Date)=>void;onRefresh:()=>void;onShare:()=>void;onLogin:()=>void;onSave:(availability:Slot[],unavailable:boolean)=>Promise<void>;onConfirm:(slot:Slot)=>Promise<void>};
function matches(slot:Slot,answer:Answer){return answer.availability?.some(s=>s.date===slot.date&&s.start<=slot.start&&s.end>=slot.end)??false;}
export default function AvailabilitySchedule({poll,answers,profile,demo,owner,week,onWeekChange,onRefresh,onShare,onLogin,onSave,onConfirm}:Props){
 const from=poll.dateFrom!,to=poll.dateTo!;
 const [date,setDate]=useState(from),[start,setStart]=useState("10:00"),[end,setEnd]=useState("11:00"),[draft,setDraft]=useState<Slot[]>([]),[unavailable,setUnavailable]=useState(false),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[saved,setSaved]=useState(false),[view,setView]=useState(()=>window.matchMedia("(max-width:600px)").matches?"list":"week");
 const [confirmOpen,setConfirmOpen]=useState(false),[finalDate,setFinalDate]=useState(from),[finalStart,setFinalStart]=useState("10:00"),[finalEnd,setFinalEnd]=useState("11:00");
 const myAnswer=profile?answers.find(a=>a.uid===profile.id):undefined,locked=!!poll.confirmedSlot;
 useEffect(()=>{setDraft(myAnswer?.availability??[]);setUnavailable(myAnswer?.unavailable??false);setDirty(false);setSaved(!!myAnswer);},[poll.id,myAnswer]);
 useEffect(()=>{setDate(from);setFinalDate(from);},[poll.id,from]);
 const displayAnswers=answers;
 const entries=displayAnswers.flatMap((a,index)=>(a.availability??[]).map(s=>({...s,name:a.name,uid:(a as Answer).uid,color:index%3}))).sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start));
 const days=Array.from({length:7},(_,i)=>new Date(week.getFullYear(),week.getMonth(),week.getDate()+i));
 const weekEnd=dateKey(days[6]),weekStart=dateKey(days[0]),previous=new Date(week);previous.setDate(previous.getDate()-1);const next=new Date(week);next.setDate(next.getDate()+7);
 const finalSlot:Slot={id:"preview",date:finalDate,start:finalStart,end:finalEnd};
 function valid(date:string,start:string,end:string){if(!date||date<from||date>to){toast.error("管理者が設定した期間内の日付を選択してください。");return false;}if(!start||!end||start>=end){toast.error("終了時刻は開始時刻より後にしてください。");return false;}return true;}
 function add(){if(!valid(date,start,end))return;if(draft.length>=100){toast.error("時間帯は100件まで登録できます。");return;}if(draft.some(s=>s.date===date&&s.start===start&&s.end===end)){toast.error("同じ時間帯がすでに追加されています。");return;}setDraft([...draft,{id:crypto.randomUUID(),date,start,end}].sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start)));setDirty(true);setSaved(false);}
 async function save(){if(demo){onLogin();return;}if(!unavailable&&!draft.length){toast.error("時間帯を追加するか、参加できる時間帯なしを選択してください。");return;}setBusy(true);try{await onSave(unavailable?[]:draft,unavailable);setDirty(false);setSaved(true);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function finalize(){if(!valid(finalDate,finalStart,finalEnd))return;setBusy(true);try{await onConfirm(finalSlot);setConfirmOpen(false);}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function chooseFinal(slot?:Slot){if(slot){setFinalDate(slot.date);setFinalStart(slot.start);setFinalEnd(slot.end);}setConfirmOpen(true);}
 function move(delta:number){const d=new Date(week);d.setDate(d.getDate()+delta*7);onWeekChange(d);}
 function renderEntry(e:typeof entries[number]){return <button key={`${e.uid??e.name}-${e.id}`} className={`availability-event color-${e.color}`} disabled={!owner||locked} onClick={()=>chooseFinal(e)}><strong>{e.start} – {e.end}</strong><span>{e.name}</span></button>;}
 return <>
  <section className="meeting availability-meeting">
   <div className="meeting-top"><div><div className="meeting-meta"><span className={locked?"status confirmed":"status"}>{locked?"日程確定":demo?"サンプル":"時間帯を受付中"}</span><span>{demo?"表示サンプル":poll.project}</span></div><h2>{poll.title}</h2><div className="meeting-facts"><span><CalendarDays size={15}/>{from.replaceAll("-","/")} – {to.replaceAll("-","/")}</span><span><Users size={15}/>{demo?"サンプル回答":`${answers.length}人が登録`}</span></div></div><div className="meeting-actions">{!demo&&<button className="quiet icon" aria-label="登録状況を再読み込み" onClick={onRefresh}><RefreshCw size={17}/></button>}<button className="quiet" onClick={onShare}><Link2 size={17}/>{demo?"日程調整を作成":"共有リンク"}</button></div></div>
   <div className="period-guide"><Clock size={16}/><span>この期間内で、参加できる時間帯を登録してください。</span></div>
   <div className="calendar-toolbar"><div className="date-navigation"><h3>{week.getFullYear()}年 <strong>{week.getMonth()+1}月</strong></h3><button className="icon" aria-label="前の週" disabled={dateKey(previous)<from} onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button className="icon" aria-label="次の週" disabled={dateKey(next)>to} onClick={()=>move(1)}><ChevronRight size={18}/></button></div><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="week">週間</TabsTrigger><TabsTrigger value="list">登録一覧</TabsTrigger></TabsList></Tabs></div>
   {view==="week"?<div className="availability-calendar-scroll"><div className="availability-calendar">{days.map(d=>{const key=dateKey(d),inside=key>=from&&key<=to;return <div className={`availability-day ${inside?"":"outside"}`} key={key}><div className={`availability-day-head ${key===dateKey(new Date())?"is-today":""}`}><span>{["日","月","火","水","木","金","土"][d.getDay()]}</span><strong>{d.getDate()}</strong></div><div className="availability-day-body">{inside?entries.filter(e=>e.date===key).map(renderEntry):<span className="day-empty">対象期間外</span>}{inside&&!entries.some(e=>e.date===key)&&<span className="day-empty">未登録</span>}</div></div>;})}</div></div>:<div className="availability-group-list">{!displayAnswers.length?<div className="availability-empty"><CalendarDays size={24}/><p>まだ時間帯が登録されていません。</p></div>:displayAnswers.map((a,i)=><div className="participant-availability" key={(a as Answer).uid??i}><h3><span className={`participant-dot color-${i%3}`}/>{a.name}</h3>{(a as Answer).unavailable?<p className="not-available">この期間に参加できる時間帯なし</p>:<div className="availability-chips">{(a.availability??[]).map(s=><span key={s.id}>{dayLabel(s.date)} <strong>{s.start} – {s.end}</strong></span>)}</div>}</div>)}</div>}
   <div className="calendar-footer"><span>{weekStart.replaceAll("-","/")} – {weekEnd.replaceAll("-","/")}</span><span>日本時間（JST）</span></div>
  </section>
  {locked?<section className="response-panel"><h2>確定した日程</h2><div className="confirmed-banner"><Check size={22}/>{dayLabel(poll.confirmedSlot!.date)} {poll.confirmedSlot!.start} – {poll.confirmedSlot!.end}</div><p className="owner-note">日程が確定したため、時間帯の登録は終了しました。</p></section>:<section className="response-panel availability-response">
   <div className="response-heading"><div><h2>{demo?"時間帯の登録イメージ":"参加できる時間帯を登録"}</h2><p>主催者：{poll.organizer} · 対象期間 {dayLabel(from)}〜{dayLabel(to)}</p></div>{!demo&&<span className="account-label">{profile?.name}として回答</span>}</div>
   <label className="availability-status-label">参加できる時間帯<Select value={unavailable?"none":"available"} onValueChange={v=>{setUnavailable(v==="none");setDirty(true);setSaved(false);}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="available">時間帯を登録する</SelectItem><SelectItem value="none">参加できる時間帯なし</SelectItem></SelectContent></Select></label>
   {!unavailable&&<><div className="availability-inputs"><label>日付<input type="date" min={from} max={to} value={date} onInput={e=>setDate(e.currentTarget.value)}/></label><label>開始時刻<input type="time" value={start} onInput={e=>setStart(e.currentTarget.value)}/></label><label>終了時刻<input type="time" value={end} onInput={e=>setEnd(e.currentTarget.value)}/></label><button className="quiet" disabled={busy} onClick={add}><Plus size={16}/>時間帯を追加</button></div><p className="form-help">複数の日付・時間帯を追加できます。追加後に「登録する」を押してください。</p><div className="availability-draft">{draft.length?draft.map(s=><div key={s.id}><CalendarDays size={17}/><strong>{dayLabel(s.date)}</strong><span>{s.start} – {s.end}</span><button aria-label={`${dayLabel(s.date)} ${s.start}から${s.end}の時間帯を削除`} disabled={busy} onClick={()=>{setDraft(draft.filter(v=>v.id!==s.id));setDirty(true);setSaved(false);}}><X size={17}/></button></div>):<div className="draft-empty">参加できる日付と時刻を追加してください。</div>}</div></>}
   {unavailable&&<p className="form-help">この期間に参加できる時間帯がないことを主催者に伝えます。</p>}
   <div className="response-submit"><span role="status">{dirty?"変更はまだ保存されていません。":saved?"登録済みです。同じLMCアカウントで更新できます。":"時間帯を追加して登録してください。"}</span><button className="primary" disabled={busy} onClick={save}>{busy?"保存中…":demo?"LMCでログインして登録":saved?"登録内容を更新":"登録する"}<Check size={17}/></button></div>
  </section>}
  {owner&&!locked&&<section className="owner-finalize"><div><h3>管理者として日程を確定</h3><p>登録された時間帯を確認して、開催日時を決められます。</p></div><button className="quiet" onClick={()=>chooseFinal()}>確定する日時を指定</button></section>}
  <Dialog open={confirmOpen} onOpenChange={setConfirmOpen}><DialogContent><DialogTitle>開催日時を確定</DialogTitle><DialogDescription>確定後は参加者の登録内容を変更できなくなります。</DialogDescription><div className="availability-inputs final-inputs"><label>日付<input type="date" min={from} max={to} value={finalDate} onInput={e=>setFinalDate(e.currentTarget.value)}/></label><label>開始時刻<input type="time" value={finalStart} onInput={e=>setFinalStart(e.currentTarget.value)}/></label><label>終了時刻<input type="time" value={finalEnd} onInput={e=>setFinalEnd(e.currentTarget.value)}/></label></div><div className="matching-answers"><strong>{answers.filter(a=>matches(finalSlot,a)).length}人の登録時間帯に含まれています</strong><p>{answers.filter(a=>matches(finalSlot,a)).map(a=>a.name).join("、")||"この時間帯に参加できる人はまだ登録されていません。"}</p></div><button className="primary" disabled={busy} onClick={finalize}>{busy?"確定中…":"この日時で確定する"}</button></DialogContent></Dialog>
 </>;
}
