import AvailabilitySchedule from "./availability-schedule";
import {auth,apiFetch,login,completeLogin,onAuthStateChanged,signOut} from "@/lib/lmc";
"use client";
import {useEffect,useState} from "react";
import {CalendarDays,Plus,ChevronLeft,ChevronRight,Link2,Clock,Check,Folder,Users,X,RefreshCw} from "lucide-react";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Toaster,toast} from "sonner";
import {type Poll,type Slot,type Answer,projects as sampleProjects,dateKey,monday,dayLabel} from "@/lib/schedule";
const choices=[{key:"yes",label:"参加できる",symbol:"○"},{key:"maybe",label:"調整できる",symbol:"△"},{key:"no",label:"参加できない",symbol:"×"}];
function timeMinutes(t:string){const [h,m]=t.split(":").map(Number);return h*60+m;}
function seed():Poll{const base=monday(new Date());const last=new Date(base);last.setDate(last.getDate()+6);return {id:"demo",title:"次のバンド練習",project:sampleProjects[0],organizer:"サンプル主催者",mode:"availability",dateFrom:dateKey(base),dateTo:dateKey(last),slots:[]};}
function sampleAnswers(poll:Poll):Answer[]{const d=new Date(poll.dateFrom!+"T12:00:00");d.setDate(d.getDate()+1);return [{name:"参加者A",choices:{},availability:[{id:"sample-a",date:poll.dateFrom!,start:"10:00",end:"12:00"}]},{name:"参加者B",choices:{},availability:[{id:"sample-b",date:poll.dateFrom!,start:"11:00",end:"13:00"},{id:"sample-c",date:dateKey(d),start:"14:00",end:"16:30"}]}];}
export default function Home(){
 const [profile,setProfile]=useState<{id:string;name:string;icon:string}|null>(null),[projectList,setProjectList]=useState<{id:string;name:string}[]>([]),[myPolls,setMyPolls]=useState<Poll[]>([]),[authReady,setAuthReady]=useState(false),[loginError,setLoginError]=useState(""),[projectOpen,setProjectOpen]=useState(false),[projectName,setProjectName]=useState("");
 const projects=profile?projectList.map(p=>p.id):sampleProjects;const label=(id:string)=>projectList.find(p=>p.id===id)?.name??id;
 const [poll,setPoll]=useState<Poll|null>(null),[answers,setAnswers]=useState<Answer[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[project,setProject]=useState(""),[week,setWeek]=useState(monday(new Date())),[view,setView]=useState(()=>window.matchMedia("(max-width:600px)").matches?"list":"week"),[open,setOpen]=useState(false),[selected,setSelected]=useState<Slot|null>(null);
 const [title,setTitle]=useState(""),[date,setDate]=useState(dateKey(new Date())),[start,setStart]=useState("10:00"),[end,setEnd]=useState("11:00"),[dateTo,setDateTo]=useState(dateKey(new Date(new Date().setDate(new Date().getDate()+6)))),[busy,setBusy]=useState(false),[votes,setVotes]=useState<Record<string,string>>({}),[sent,setSent]=useState(false),[sharing,setSharing]=useState(false);
 const active=poll??seed(),demo=!poll,owner=!!profile&&profile.id===poll?.ownerId,shown=active.slots.filter(s=>demo?(!project||active.project===label(project)):true);const displayedAnswers=demo?sampleAnswers(active):answers;const days=Array.from({length:7},(_,i)=>new Date(week.getFullYear(),week.getMonth(),week.getDate()+i));
 async function refresh(id:string){setLoading(true);setError("");try{const r=await apiFetch(`/polls/${encodeURIComponent(id)}`);const b=await r.json();if(!r.ok)throw new Error(b.error);setPoll(b.poll);setAnswers(b.answers);setProject(b.poll.projectId??b.poll.project);const mine=b.answers?.find((a:Answer)=>a.uid===auth.currentUser?.uid);setVotes(mine?.choices??{});setSent(!!mine);setWeek(monday(new Date((b.poll.dateFrom??b.poll.slots[0]?.date??dateKey(new Date()))+"T12:00:00")));}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{let unsubscribe=()=>{};let stopped=false;(async()=>{try{await completeLogin();unsubscribe=onAuthStateChanged(auth,async user=>{if(stopped)return;try{if(user){const r=await apiFetch("/bootstrap");const b=await r.json();if(!r.ok)throw new Error(b.error);setProfile(b.profile);setProjectList(b.projects);setMyPolls(b.polls);setProject(b.projects[0]?.id??"");const id=new URLSearchParams(location.search).get("poll");if(id)await refresh(id);}else{setProfile(null);}setLoginError("");}catch(e){setLoginError((e as Error).message);setProfile(null);}finally{setAuthReady(true);}});}catch(e){setLoginError((e as Error).message);setAuthReady(true);}})();return()=>{stopped=true;unsubscribe();};},[]);
 async function startLogin(){try{await login();}catch(e){toast.error((e as Error).message);}}
 async function addProject(){if(!projectName.trim())return;setBusy(true);try{const r=await apiFetch("/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:projectName})});const b=await r.json();if(!r.ok)throw new Error(b.error);setProjectList([...projectList,b.project]);setProject(b.project.id);setProjectName("");setProjectOpen(false);toast.success("プロジェクトを作成しました。");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!ctx)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:"read_schedule",description:"表示中の日付の期間と登録された参加可能な時間帯を取得します。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("入力は空のオブジェクトにしてください。");return {demo,poll:active,answers:displayedAnswers};}},{signal:lifecycle.signal})).catch(()=>{});return ()=>lifecycle.abort();},[poll,answers]);
 function move(delta:number){const d=new Date(week);d.setDate(d.getDate()+delta*7);setWeek(d);}
 function begin(d?:Date){if(!profile){startLogin();return;}if(!projectList.length){setProjectOpen(true);return;}if(!projectList.some(p=>p.id===project))setProject(projectList[0].id);const first=d??new Date();const last=new Date(first);last.setDate(last.getDate()+6);setDate(dateKey(first));setDateTo(dateKey(last));setOpen(true);}
 async function create(){if(!title.trim()||!project||!date||!dateTo){toast.error("会議名・プロジェクトと日付の期間を入力してください。");return;}if(date>dateTo){toast.error("終了日は開始日以降の日付を選択してください。");return;}setBusy(true);try{const r=await apiFetch("/polls",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,projectId:project,mode:"availability",dateFrom:date,dateTo})});const b=await r.json();if(!r.ok)throw new Error(b.error);setPoll(b.poll);setMyPolls([b.poll,...myPolls]);setAnswers([]);setVotes({});setSent(false);setWeek(monday(new Date((b.poll.dateFrom??b.poll.slots[0]?.date??dateKey(new Date()))+"T12:00:00")));history.replaceState(null,"",`?poll=${b.poll.id}`);setOpen(false);setSharing(true);toast.success("日程調整を作成しました。");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 function shareUrl(){return `${location.origin}${import.meta.env.BASE_URL}?poll=${active.id}`;}
 async function copy(management=false){try{await navigator.clipboard.writeText(shareUrl());toast.success(management?"主催者リンクをコピーしました。":"回答リンクをコピーしました。");}catch{toast.error("コピーできませんでした。表示されたリンクをコピーしてください。");}}
 async function respond(){if(!active.slots.every(s=>votes[s.id])){toast.error("名前と、すべての候補への回答を入力してください。");return;}setBusy(true);try{const r=await apiFetch(`/polls/${active.id}/answers`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({choices:votes})});const b=await r.json();if(!r.ok)throw new Error(b.error);await refresh(active.id);setSent(true);toast.success("回答を保存しました。");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function confirm(slot:Slot){setBusy(true);try{const r=await apiFetch(`/polls/${active.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({slotId:slot.id})});const b=await r.json();if(!r.ok)throw new Error(b.error);setPoll(b.poll);setSelected(null);toast.success("日程を確定しました。");}catch(e){toast.error((e as Error).message);}finally{setBusy(false);}}
 async function saveAvailability(availability:Slot[],unavailable:boolean){const r=await apiFetch(`/polls/${active.id}/answers`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({availability,unavailable})});const b=await r.json();if(!r.ok)throw new Error(b.error);await refresh(active.id);toast.success("参加できる時間帯を登録しました。");}
 async function confirmAvailability(slot:Slot){const r=await apiFetch(`/polls/${active.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({slot})});const b=await r.json();if(!r.ok)throw new Error(b.error);setPoll(b.poll);setMyPolls(myPolls.map(p=>p.id===b.poll.id?b.poll:p));toast.success("開催日時を確定しました。");}
 function download(){const slot=active.slots.find(s=>s.id===active.confirmed);if(!slot)return;const fmt=(s:string)=>s.replace(/[-:]/g,"")+"00";const escape=(s:string)=>s.replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//LMC Schedule//JA","BEGIN:VEVENT",`UID:${active.id}@lmc-schedule`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d+/,"")}`,`DTSTART:${fmt(new Date(`${slot.date}T${slot.start}:00+09:00`).toISOString().slice(0,16))}Z`,`DTEND:${fmt(new Date(`${slot.date}T${slot.end}:00+09:00`).toISOString().slice(0,16))}Z`,`SUMMARY:${escape(active.title)}`,"END:VEVENT","END:VCALENDAR"].join("\r\n");const url=URL.createObjectURL(new Blob([ics],{type:"text/calendar;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="lmc-meeting.ics";a.click();URL.revokeObjectURL(url);}
 const fromHour=Math.min(8,...shown.map(s=>Math.floor(timeMinutes(s.start)/60))),toHour=Math.max(19,...shown.map(s=>Math.ceil(timeMinutes(s.end)/60))),range=toHour-fromHour;
 return <div className="app-shell"><Toaster position="top-center" richColors/><aside className="sidebar"><a className="brand" href={import.meta.env.BASE_URL}><span className="logo"><CalendarDays size={21}/></span><span>LMC<span className="brand-sub">Schedule</span></span></a><div className="workspace"><span className="workspace-mark">L</span><div>LMC ワークスペース<small>日程調整</small></div></div><p className="nav-label">WORKSPACE</p><div className="nav-active"><CalendarDays size={18}/> 日程調整</div><div className="side-projects"><p className="nav-label">プロジェクト <button className="new-project-button" aria-label="プロジェクトを作成" onClick={()=>profile?setProjectOpen(true):startLogin()}><Plus size={15}/></button></p>{projects.map((p,i)=><button key={p} className={project===p?"project active":"project"} onClick={()=>{setProject(p);setPoll(null);setAnswers([]);setVotes({});setSent(false);history.replaceState(null,"",location.pathname);}}><i style={{background:["#5974ef","#bd73ca","#ea9c45"][i]}}/>{label(p)}</button>)}</div>{profile&&myPolls.length>0&&<div className="my-polls"><p className="nav-label">作成した日程調整</p>{myPolls.filter(p=>!project||p.projectId===project).map(p=><button key={p.id} onClick={()=>{history.replaceState(null,"",`?poll=${p.id}`);refresh(p.id);}}>{p.title}<small>{(p.confirmed||p.confirmedSlot)?"確定":"回答受付中"}</small></button>)}</div>}<div className="mini-cal"><div>{week.getFullYear()}年 {week.getMonth()+1}月</div><div className="mini-grid">{"月火水木金土日".split("").map(d=><small key={d}>{d}</small>)}{Array.from({length:35},(_,i)=>{const first=new Date(week.getFullYear(),week.getMonth(),1);const d=new Date(first);d.setDate(i-((first.getDay()+6)%7)+1);return <button key={i} className={dateKey(d)===dateKey(new Date())?"today":""} onClick={()=>setWeek(monday(d))}>{d.getMonth()===week.getMonth()?d.getDate():""}</button>;})}</div></div><div className="account"><span className="avatar">{profile?.name.slice(0,1)??"L"}</span><div>{profile?.name??"LMC アカウント"}<small>{profile?"LMC 連携済み":"未ログイン"}</small></div>{profile&&<button className="logout" onClick={()=>signOut(auth).then(()=>location.assign(import.meta.env.BASE_URL))}>ログアウト</button>}</div></aside>
 <div className="main"><header className="topbar"><span><CalendarDays size={18}/> 日程調整</span><span className="top-note">{profile?<><span>{profile.name}</span><span className="top-avatar">{profile.name.slice(0,1)}</span></>:<button className="quiet" disabled={!authReady} onClick={startLogin}>{authReady?"LMCでログイン":"確認中…"}</button>}</span></header><main><div className="page-heading"><div><div className="eyebrow">SCHEDULE TOGETHER</div><h1>みんなの予定を、ひとつに。</h1><p>プロジェクトを選んで、次のミーティングを決めましょう。</p></div><button className="primary" onClick={()=>begin()}><Plus size={18}/>日程調整を作成</button></div>
 {loginError&&<div className="error" role="alert">{loginError}<button onClick={startLogin}>再ログイン</button></div>}{!profile?<div className="integration"><span className="integration-icon"><Folder size={18}/></span><span><strong>LMCアカウントで日程調整</strong><span> 登録済みの名前を使って、プロジェクトの作成・回答ができます。</span></span><button className="quiet" disabled={!authReady} onClick={startLogin}>ログイン</button></div>:<div className="signed-in-banner"><Check size={16}/>LMC アカウント連携済み <span>回答者：{profile.name}</span></div>}
 <div className="filter-row"><div className="project-picker"><span>プロジェクト</span><Select value={project} onValueChange={v=>{setProject(v);if(poll){setPoll(null);setAnswers([]);history.replaceState(null,"",location.pathname);}}}><SelectTrigger><SelectValue placeholder="プロジェクトを選択"/></SelectTrigger><SelectContent>{projects.map(p=><SelectItem key={p} value={p}>{label(p)}</SelectItem>)}{poll?.projectId&&!projects.includes(poll.projectId)&&<SelectItem value={poll.projectId}>{poll.project}</SelectItem>}</SelectContent></Select><button className="icon" aria-label="新しいプロジェクト" onClick={()=>profile?setProjectOpen(true):startLogin()}><Plus size={18}/></button></div><span className="timezone"><Clock size={15}/> 日本時間（JST）</span></div>
 {loading?<div className="notice" role="status">日程調整を読み込んでいます…</div>:error?<div className="error" role="alert">{error}<button onClick={()=>refresh(new URLSearchParams(location.search).get("poll")??"")}>再読み込み</button></div>:<>{active.mode==="availability"&&(!demo||!profile)&&<AvailabilitySchedule poll={active} answers={displayedAnswers} profile={profile} demo={demo} owner={owner} week={week} onWeekChange={setWeek} onRefresh={()=>refresh(active.id)} onShare={()=>demo?begin():setSharing(true)} onLogin={startLogin} onSave={saveAvailability} onConfirm={confirmAvailability}/>} {active.mode!=="availability"&&(!demo||!profile)&&<section className="meeting"><div className="meeting-top"><div><div className="meeting-meta"><span className={active.confirmed?"status confirmed":"status"}>{active.confirmed?"日程確定":demo?"サンプル":"回答受付中"}</span><span>{demo?"表示サンプル":active.project}</span></div><h2>{active.title}</h2><div className="meeting-facts"><span><Clock size={15}/>{active.slots.length}件の候補日時</span><span><Users size={15}/>{answers.length}人が回答</span></div></div><div className="meeting-actions">{!demo&&<button className="quiet icon" aria-label="回答を更新" onClick={()=>refresh(active.id)}><RefreshCw size={17}/></button>}<button className="quiet" onClick={()=>demo?begin():setSharing(true)}><Link2 size={17}/>{demo?"新しく作成して共有":"共有リンク"}</button></div></div>
 <div className="calendar-toolbar"><div className="date-navigation"><h3>{week.getFullYear()}年 <strong>{week.getMonth()+1}月</strong></h3><button className="icon" aria-label="前の週" onClick={()=>move(-1)}><ChevronLeft size={18}/></button><button className="icon" aria-label="次の週" onClick={()=>move(1)}><ChevronRight size={18}/></button><button className="today-button" onClick={()=>setWeek(monday(new Date()))}>今日</button></div><Tabs value={view} onValueChange={setView}><TabsList><TabsTrigger value="week">週間</TabsTrigger><TabsTrigger value="list">候補一覧</TabsTrigger></TabsList></Tabs></div>
 {view==="week"?<div className="calendar-scroll"><div className="calendar" style={{gridTemplateColumns:"58px repeat(7,minmax(108px,1fr))"}}><div className="day-head timezone-mini">JST</div>{days.map(d=><div className={`day-head ${dateKey(d)===dateKey(new Date())?"is-today":""}`} key={dateKey(d)}><span>{["日","月","火","水","木","金","土"][d.getDay()]}</span><strong>{d.getDate()}</strong></div>)}<div className="time-column" style={{height:range*64}}>{Array.from({length:range},(_,i)=><span key={i} style={{top:i*64}}>{String(fromHour+i).padStart(2,"0")}:00</span>)}</div>{days.map(d=><div className={`day-column ${dateKey(d)===dateKey(new Date())?"current-day":""}`} style={{height:range*64}} key={dateKey(d)}>{Array.from({length:range},(_,h)=><button key={h} className="hour-cell" style={{top:h*64}} aria-label={`${dayLabel(dateKey(d))} ${fromHour+h}時の候補を追加`} disabled={!demo} onClick={()=>{setStart(`${String(fromHour+h).padStart(2,"0")}:00`);setEnd(`${String(Math.min(23,fromHour+h+1)).padStart(2,"0")}:00`);begin(d);}}/>)}{shown.filter(s=>s.date===dateKey(d)).map((s,i)=><button className={`event event-${shown.indexOf(s)%3} ${active.confirmed===s.id?"event-confirmed":""}`} key={s.id} onClick={()=>setSelected(s)} style={{top:(timeMinutes(s.start)-fromHour*60)*64/60+2,height:Math.max(40,(timeMinutes(s.end)-timeMinutes(s.start))*64/60-4)}}><span>{s.start} – {s.end}</span><strong>{active.confirmed===s.id?"確定日時":"候補日時"}</strong><small>{answers.filter(a=>a.choices[s.id]==="yes").length}人が参加可能</small></button>)}</div>)}</div></div>:<div className="slot-list">{active.slots.map(s=><button key={s.id} className="slot-list-item" onClick={()=>setSelected(s)}><CalendarDays size={20}/><span><strong>{dayLabel(s.date)}</strong><small>{s.start} – {s.end}</small></span><span>{answers.filter(a=>a.choices[s.id]==="yes").length}人が参加可能</span></button>)}</div>}
 <div className="calendar-footer"><span><i/> 候補日時</span><span>候補をタップして詳細を確認</span></div></section>}
 {demo&&profile?<section className="project-empty"><span className="hint-icon"><CalendarDays size={24}/></span><h2>{projectList.length?`${label(project)}の日程調整`:"最初のプロジェクトを作成しましょう"}</h2><p>{projectList.length?"対象の日付の期間を設定し、参加できる時間帯を集められます。":"バンド練習やライブ準備など、日程調整をまとめるプロジェクトを作成します。"}</p><button className="primary" onClick={()=>begin()}><Plus size={17}/>{projectList.length?"日程調整を作成":"プロジェクトを作成"}</button>{myPolls.filter(p=>!project||p.projectId===project).length>0&&<div className="poll-card-list">{myPolls.filter(p=>!project||p.projectId===project).map(p=><button key={p.id} onClick={()=>{history.replaceState(null,"",`?poll=${p.id}`);refresh(p.id);}}><strong>{p.title}</strong><span>{p.mode==="availability"?`${dayLabel(p.dateFrom!)}〜${dayLabel(p.dateTo!)}`:`${p.slots.length}件の候補`} · {(p.confirmed||p.confirmedSlot)?"確定":"回答受付中"}</span></button>)}</div>}</section>:demo?<div className="start-hint"><div><span className="hint-icon"><Link2 size={22}/></span><div><h3>期間を決めて、参加できる時間を集める。</h3><p>参加者が期間内の日付と開始・終了時刻を登録します。</p></div></div><button onClick={()=>begin()}>最初の日程調整を作成<Plus size={16}/></button></div>:active.mode==="availability"?null:<section className="response-panel"><div className="response-heading"><div><h2>{active.confirmed?"確定した日程":owner?"回答状況":"候補日時に回答する"}</h2><p>主催者：{active.organizer} · 日本時間（JST）</p></div>{active.confirmed&&<button className="quiet" onClick={download}><CalendarDays size={17}/>カレンダーに追加</button>}</div>{active.confirmed?<div className="confirmed-banner"><Check size={22}/>{(()=>{const s=active.slots.find(s=>s.id===active.confirmed)!;return `${dayLabel(s.date)} ${s.start} – ${s.end}`;})()}</div>:<><div className="name-field">回答者：<strong>{profile?.name}</strong>（LMCアカウント）</div><div className="vote-list">{active.slots.map(s=><div className="vote-row" key={s.id}><div><strong>{dayLabel(s.date)}</strong><span>{s.start} – {s.end}</span></div><div className="vote-options">{choices.map(c=><button aria-pressed={votes[s.id]===c.key} className={votes[s.id]===c.key?`vote chosen ${c.key}`:"vote"} key={c.key} onClick={()=>{setVotes({...votes,[s.id]:c.key});setSent(false);}}><strong>{c.symbol}</strong><span>{c.label}</span></button>)}</div></div>)}</div><div className="response-submit"><span>{sent?"回答を保存しました。同じLMCアカウントで更新できます。":"すべての候補に回答してください。"}</span><button className="primary" disabled={busy} onClick={respond}>{busy?"保存中…":sent?"回答を更新":"回答を送信"}<Check size={17}/></button></div></>}{answers.length>0&&<div className="results-scroll"><table><caption>参加者の回答</caption><thead><tr><th>参加者</th>{active.slots.map(s=><th key={s.id}>{dayLabel(s.date)}<small>{s.start} – {s.end}</small></th>)}</tr></thead><tbody>{answers.map((a,i)=><tr key={i}><th>{a.name}</th>{active.slots.map(s=><td key={s.id}>{choices.find(c=>c.key===a.choices[s.id])?.symbol}</td>)}</tr>)}</tbody></table></div>}{owner&&!active.confirmed&&<p className="owner-note">候補日時を選ぶと、主催者として日程を確定できます。</p>}</section>}</>}
 <footer className="page-footer"><span>LMC Schedule</span><span>予定を合わせて、プロジェクトを前へ。</span></footer></main></div>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="create-dialog"><DialogTitle>日程調整を作成</DialogTitle><DialogDescription>管理者が日付の期間を設定します。参加者は、その期間内で参加できる時間帯を登録します。</DialogDescription><div className="form-fields"><label>会議名<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="例：次のバンド練習"/></label><label>プロジェクト<Select value={project} onValueChange={setProject}><SelectTrigger><SelectValue placeholder="プロジェクトを選択"/></SelectTrigger><SelectContent>{projects.map(p=><SelectItem key={p} value={p}>{label(p)}</SelectItem>)}</SelectContent></Select></label><div className="form-account">主催者：{profile?.name}（LMCアカウント）</div><div className="period-fields"><label>開始日<input type="date" value={date} onInput={e=>{setDate(e.currentTarget.value);if(e.currentTarget.value>dateTo)setDateTo(e.currentTarget.value);}}/></label><label>終了日<input type="date" min={date} value={dateTo} onInput={e=>setDateTo(e.currentTarget.value)}/></label></div><p className="form-help">開始日・終了日を含む期間です。時間帯は参加者が回答時に指定します。</p><button className="primary wide" disabled={busy} onClick={create}>{busy?"作成中…":"日程調整を作成してリンクを発行"}</button></div></DialogContent></Dialog>
 <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent><DialogTitle>{selected&&dayLabel(selected.date)}</DialogTitle><DialogDescription>{selected?.start} – {selected?.end}（日本時間）</DialogDescription><p>{selected&&answers.filter(a=>a.choices[selected.id]==="yes").length}人が参加可能です。</p>{demo?<button className="primary" onClick={()=>{setSelected(null);begin();}}>自分の日程調整を作成</button>:owner&&!active.confirmed?<button className="primary" disabled={busy} onClick={()=>selected&&confirm(selected)}>この日時で確定する</button>:<p>画面下の回答欄で参加可否を選択してください。</p>}</DialogContent></Dialog>
 <Dialog open={projectOpen} onOpenChange={setProjectOpen}><DialogContent><DialogTitle>プロジェクトを作成</DialogTitle><DialogDescription>日程調整をプロジェクトごとにまとめます。</DialogDescription><label>プロジェクト名<input maxLength={80} value={projectName} onChange={e=>setProjectName(e.target.value)} placeholder="例：秋ライブ・バンド練習"/></label><button className="primary" disabled={busy||!projectName.trim()} onClick={addProject}>{busy?"作成中…":"プロジェクトを作成"}</button></DialogContent></Dialog>
 <Dialog open={sharing} onOpenChange={setSharing}><DialogContent><DialogTitle>回答リンクを共有</DialogTitle><DialogDescription>このリンクを開き、LMCでログインすると、期間内の参加できる時間帯を登録できます。</DialogDescription>{!demo&&<><input aria-label="回答リンク" readOnly value={typeof window!=="undefined"?shareUrl():""}/><button className="primary" onClick={()=>copy()}><Link2 size={17}/>回答リンクをコピー</button>{owner&&<div className="management-link"><h3>主催者として開く</h3><p>同じリンクでも、主催者のLMCアカウントでは日程を確定できます。</p><input aria-label="管理リンク" readOnly value={typeof window!=="undefined"?shareUrl():""}/><button className="quiet" onClick={()=>copy(true)}>主催者リンクをコピー</button></div>}</>}</DialogContent></Dialog>
 </div>;
}
