import {initializeApp} from "firebase/app";
import {getAuth,signInWithCustomToken,onAuthStateChanged,signOut} from "firebase/auth";
export const auth=getAuth(initializeApp({apiKey:"AIzaSyAWtITnn5uMOPBgOY0Bd7Rt5IN1ry8XoJI",authDomain:"urakata-app.firebaseapp.com",projectId:"urakata-app",appId:"1:407777765696:web:045c2d94729022b4eab2a5"}));
export {onAuthStateChanged,signOut};
const endpoint="https://asia-northeast1-urakata-app.cloudfunctions.net/lmcScheduleApi";
export async function apiFetch(path:string,options:RequestInit={}){const token=await auth.currentUser?.getIdToken();if(!token)throw new Error("LMCアカウントでログインしてください。");return fetch(endpoint+path,{...options,headers:{...options.headers,"Authorization":`Bearer ${token}`}});}
function base64url(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");}
export async function login(){const state=base64url(crypto.getRandomValues(new Uint8Array(32))),verifier=base64url(crypto.getRandomValues(new Uint8Array(48)));const challenge=base64url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(verifier))));sessionStorage.setItem("lmc-schedule-login",JSON.stringify({state,verifier,returnSearch:location.search}));const url=new URL("https://lmc-mobile.sorairosystem.com/schedule-authorize.html");Object.entries({response_type:"code",client_id:"lmc-schedule",redirect_uri:"https://erdaosataillang.github.io/lmc-schedule/",state,code_challenge:challenge,code_challenge_method:"S256"}).forEach(([k,v])=>url.searchParams.set(k,v));location.assign(url.toString());}
export async function completeLogin(){const params=new URLSearchParams(location.search),code=params.get("lmc_code");if(!code)return;const stored=sessionStorage.getItem("lmc-schedule-login");if(!stored)throw new Error("ログインの確認に失敗しました。もう一度ログインしてください。");const state=JSON.parse(stored);if(state.state!==params.get("state"))throw new Error("ログインの確認に失敗しました。もう一度ログインしてください。");const r=await fetch(endpoint+"/auth/exchange",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({code,codeVerifier:state.verifier,redirectUri:"https://erdaosataillang.github.io/lmc-schedule/"})});const b=await r.json();if(!r.ok)throw new Error(b.error);await signInWithCustomToken(auth,b.customToken);sessionStorage.removeItem("lmc-schedule-login");history.replaceState(null,"",location.pathname+(state.returnSearch||""));}
